AllCops:
  Exclude:
    - spec/**/*.rb
Metrics/LineLength:
  Max: 140
Style/AndOr:
  Enabled: false
Style/BlockDelimiters:
  EnforcedStyle: semantic
  IgnoredMethods:
    # Defaults:
    - lambda
    - proc
    - it
    # Ours:
    - MatchEitherResult
    - match
    - specify
Style/Lambda:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/StabbyLambdaParentheses:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Specific exclusions
Style/MethodName:
  Exclude:
    - lib/either_result_matcher.rb
